server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/wx-pay?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: cn.zjy.wxpay.demo
  configuration:
    map-underscore-to-camel-case: true

wx:
  miniapp:
    appid: #appid
    secret: #secret
    aesKey: #微信小程序消息服务器配置的EncodingAESKey
    msgDataFormat: JSON
    mchId: #微信支付商户号
    mchKey:  #微信支付商户密钥
    keyPath: # p12证书的位置 绝对位置相对位置都行
